### ISSUE TITLE
bitwise.byte.read(17) => Cannot read property 'read' of undefined

### ISSUE THREAD

**Issue by alexis57** [dodekeract/bitwise#3]
I had used to be happy with bitwise but this code doesn't work anymore.

```js
const bitwise = require('bitwise')

let binFlags = bitwise.byte.read(17)

console.log(binFlags)
```

```
let binFlags = bitwise.byte.read(17)
                           ^

TypeError: Cannot read property 'read' of undefined
```

I've used to use `readByte` from version < 1.0.0 but this function disappeared.

**Comment by dodekeract** [comment]
It's an easy fix, you're using the legacy `require` way of importing packages. Since `bitwise` uses `import` now, you'd have to either switch to that, or use the following:

```js
const readByte = require('bitwise/byte/read').default
readByte()

// or

const byte = require('bitwise/byte').default
byte.read()

// or

const bitwise = require('bitwise').default
bitwise.byte.read()
```

This is not specific to `bitwise` and can't be avoided, you'll find it in a lot of modern libraries. It's because ES imports support multiple exports, with `default` being the default export.

I'll add this to the documentation, let me know if this solved the issue for you.

**Comment by alexis57** [comment]
I see, great! Thank you for the explanation and good job with your library!

**Comment by dodekeract** [comment]
@alexis57 I updated bitwise and starting with version `1.4.0`, you should be able to omit `.default`. Please open an issue if that doesn't work for you.
